version: 0.0
Resources:
  - MyNginxContainer:
      Type: AWS::CodeDeploy::Instance
      Properties:
        Image: nginx:latest
        EnvironmentVariables:
          - Name: EXAMPLE_ENV
            Value: "example-value"
